name: Chorus

on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build-chorus:
    name: Build Chorus
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Chorus
        run: ./gradlew build

  release-chorus:
      name: Release Chorus
      timeout-minutes: 10
      runs-on: ubuntu-latest
      needs: build-chorus
      if: github.repository == 'Chorus-OSS/Chorus' && github.ref_name == 'main'
      steps:
        - name: Upload Chorus artifact
          uses: actions/upload-artifact@v4
          with:
            name: Chorus
            path: build/chorus.jar

        - name: Release Snapshot
          uses: softprops/action-gh-release@v1
          with:
            tag_name: snapshot
            name: "Latest Snapshot"
            body: |
              Latest version of Chorus.
              
              **Commit:** https://github.com/Chorus-OSS/Chorus/commit/${{ github.sha }}
            files: build/chorus.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}