name: Chorus

on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: write

jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed-files.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/**
            gradle/**
            build.gradle.kts
            settings.gradle.kts

  build-chorus:
    name: Build Chorus
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Chorus
        run: ./gradlew build

      - name: Upload Chorus artifact
        uses: actions/upload-artifact@v4
        with:
          name: chorus
          path: build/chorus.jar

  release-chorus:
      name: Release Chorus
      timeout-minutes: 10
      runs-on: ubuntu-latest
      needs: build-chorus
      if: github.repository == 'Chorus-OSS/Chorus' && github.ref_name == 'main'
      steps:
        - name: Download Chorus artifact
          uses: actions/download-artifact@v4
          with:
            name: chorus

        - name: Release Snapshot
          uses: softprops/action-gh-release@v1
          with:
            tag_name: snapshot
            name: "Latest Snapshot"
            body: |
              Latest version of Chorus.
              
              **Commit:** https://github.com/Chorus-OSS/Chorus/commit/${{ github.sha }}
            files: chorus.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - uses: actions/checkout@v4
          with:
            fetch-tags: true

        - name: Bump Tag
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -fa snapshot "$GITHUB_SHA" -m "Latest snapshot build of Chorus"
            git push -f origin snapshot